name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build and push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: 3434dea/cloud9:latest
